name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  playwrighttests:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.1-focal
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          echo "Start the shopping store application"
          ./shopping-store-linux-amd64 &
          chmod +x ./shopping-store-linux-amd64 && ./shopping-store-linux-amd64 &
          npm ci
          echo "Run playwright tests"
          npm run test:ci
